import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import AuthGate from "../components/AuthGate";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
});
const jetBrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${jetBrainsMono.variable} h-dvh w-full bg-grayscale-1`}>
				<AuthGate>{children}</AuthGate>
			</body>
		</html>
	);
}
